### ISSUE TITLE
Manager Classes: Not all managers prevent changing mandatory fields to null

### ISSUE THREAD

**Issue by katharinabassler** [dlr-eoc/prosEO#174]
Some manager classes, such as the ProcessorManager, do not prevent null values for mandatory fields after modification.

**Comment by tangobravo62** [comment]
Code inspected and updated, relaxed requirements tested with creation of PTM mission from scratch.

Testing of the mandatory values check is not easy, since if called via REST API, mostly Spring Boot already catches incomplete requests, so the new code is not executed.

No further action required, therefore closing this issue.
